In [1]:
pip install google-play-scraper

Requirement already satisfied: google-play-scraper in c:\laragon\bin\python\python-3.10\lib\site-packages (1.2.7)
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution -vicorn (c:\laragon\bin\python\python-3.10\lib\site-packages)
WARNING: Ignoring invalid distribution -vicorn (c:\laragon\bin\python\python-3.10\lib\site-packages)
WARNING: Ignoring invalid distribution -vicorn (c:\laragon\bin\python\python-3.10\lib\site-packages)

[notice] A new release of pip is available: 25.1.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
from google_play_scraper import Sort, reviews
from google_play_scraper import app
import pandas as pd
import numpy as np

In [3]:
result, continuation_token = reviews(
    'com.djinggamedia.denpasarsightseeing',
    lang='id', # Bahasa
    country='id', # Negara
    sort=Sort.MOST_RELEVANT, # Sorting yang paling relevan
    count=500, # Jumlah dataset
    filter_score_with= None
)

In [4]:
# Dataframe
data = pd.DataFrame(np.array(result),columns=['review'])
data = data.join(pd.DataFrame(data.pop('review').tolist()))
data.head()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,b3866c43-bd09-4f67-9e78-e3cc75af24f0,Gunggek Putri,https://play-lh.googleusercontent.com/a-/ALV-U...,"Kepada pihak terkait, saya gagal mengajukan pe...",3,1,3.5.12,2025-12-03 22:36:35,None,NaT,3.5.12
1,560c50fd-581d-4e7a-bc66-858f09319d82,alivia khumairoh,https://play-lh.googleusercontent.com/a/ACg8oc...,"udah bikin akun , tapi gak bisa login karna em...",2,1,3.5.12,2026-03-24 11:40:42,None,NaT,3.5.12
2,2dff623f-b3b8-460b-8845-1167c5b929b5,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Saat membuat pengaduan aplikasi tiba2 crash da...,1,5,3.2,2020-01-10 21:19:01,"Mohon maaf atas ketidaknyamanannya, kami akan ...",2024-04-18 15:04:13,3.2
3,9fd377e8-d18d-48b9-96b2-a413877ff0b8,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"menu Daftar masih eror, Menu Live CCTV masih E...",2,5,2.8,2019-01-23 01:21:20,"Mohon maaf atas ketidaknyamanannya, kami akan ...",2024-03-19 09:06:55,2.8
4,c5ec6e33-ee7e-41d8-be6e-867100496e91,Wayan BudhiSetiawan,https://play-lh.googleusercontent.com/a-/ALV-U...,1 bintang dulu ya. Tiang sudah dari kemarin do...,1,16,3.4,2021-01-19 06:15:09,"Terimakasih atas masukkannya, mohon maaf atas ...",2024-03-15 10:47:41,3.4

In [5]:
len(data)

157

In [6]:
data = data[['content','score']]
data.head()

                                             content  score
0  Kepada pihak terkait, saya gagal mengajukan pe...      3
1  udah bikin akun , tapi gak bisa login karna em...      2
2  Saat membuat pengaduan aplikasi tiba2 crash da...      1
3  menu Daftar masih eror, Menu Live CCTV masih E...      2
4  1 bintang dulu ya. Tiang sudah dari kemarin do...      1

In [7]:
data = data.rename(columns={'content': 'ulasan', 'score': 'rating'}) # Mengganti nama fitur
data.head()

                                              ulasan  rating
0  Kepada pihak terkait, saya gagal mengajukan pe...       3
1  udah bikin akun , tapi gak bisa login karna em...       2
2  Saat membuat pengaduan aplikasi tiba2 crash da...       1
3  menu Daftar masih eror, Menu Live CCTV masih E...       2
4  1 bintang dulu ya. Tiang sudah dari kemarin do...       1

In [8]:
# Labeling sentimen berdasarkan rating
def label_sentiment(rating):
    if rating in [1, 2]:
        return 'Negatif'
    elif rating == 3:
        return 'Netral'
    elif rating in [4, 5]:
        return 'Positif'

# Terapkan ke kolom rating
data['sentiment'] = data['rating'].apply(label_sentiment)

# Melihat hasil
print(data[['rating', 'sentiment']].head())

   rating sentiment
0       3    Netral
1       2   Negatif
2       1   Negatif
3       2   Negatif
4       1   Negatif

In [9]:
data.to_csv("UlasanDPS.csv", index = False  , encoding='utf-8')